###########
# site.title

title: Harsh Raj
description: A developer -- complete this line
baseurl: "/Portfolio-Website" # the subpath of your site, e.g. /blog/
url: "https://harshraj2717.github.io/Portfolio-Website" # the base hostname & protocol for your site
# host: 0.0.0.0


#########################
# more settings

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

markdown: kramdown

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

# sass:
#   sass_dir: css
#   style:    compressed

collections:
  my_tags:
    output: true
    permalink: /tagged/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

# baseurl: ""
permalink: /blog/:slug
timezone: India/Kolkata
future: false

exclude:
- README.md
- LICENSE.md
- vendor

Projects: /projects
Blog: /blog

# Add general links to site pages here
links:
  Resume: /assets/resume.pdf

# Add links for more focus here
special_links:
  <img src="/Portfolio-Website/assets/logos/main.png" alt="Mail" width=20px height=20px />: mailto:harshraj2717@gmail.com
  <img src="/Portfolio-Website/assets/logos/github.png" alt="GitHub" width=20px height=20px />: https://github.com/HarshRaj2717
  <img src="/Portfolio-Website/assets/logos/linkedin.png" alt="LinkedIn" width=20px height=20px />: https://www.linkedin.com/in/harshraj2717/
  <img src="/Portfolio-Website/assets/logos/discord.png" alt="Discord" width=20px height=20px />: https://www.linkedin.com/in/harshraj2717/
